name: build snap package
on:
  push:
    branches: [main]
    pull_request:
      types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Architecture:
          - amd64
          - arm64
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: diddlesnaps/snapcraft-multiarch-action@v1
      id: snapcraft
      with:
        architecture: ${{ matrix.architecture }}
